@startuml JobFair Class Diagram
left to right direction
skinparam classAttributeIconSize 0

package "JobFair" {

  class "<<Application>>\nJobFairService" as JobFairService {}


  ' Companies

  class "<<Resource>>\nCompanies" as ResourceCompanies{
    <<GET>> +getCompanies(): Company
    <<POST>> +createCompany(): Company
  }

  class "<<Resource>>\nCompany" as ResourceCompany {
    <<GET>> +getCompany(): Company
    <<PUT>> +updateCompany(): Company
    <<DELETE>> +deleteCompany(): void
  }

  class "<<Representation>>\nCompany" as RepresentationCompany {
    -name
    -address
    -website
    -description
    -telephone
  }


  ' Authentication

  class "<<Resource>>\nAuthentication" as ResourceAuth {
    <<POST>> +registerUser(): Token
    <<POST>> +login(): Token
    <<GET>> +getMe(): User
    <<GET>> +logout(): void
  }

  class "<<Representation>>\nUser" as RepresentationUser {
    -name
    -email
    -phone
    -role
    -createdAt
  }

  class "<<Representation>>\nToken" as RepresentationToken {
    -success
    -token
  }


  ' Bookings

  class "<<Resource>>\nBookings" as ResourceBookings {
    <<GET>> +getBookings(): Booking
  }

  class "<<Resource>>\nBooking" as ResourceBooking {
    <<GET>> +getBooking(): Booking
    <<PUT>> +updateBooking(): Booking
    <<DELETE>> +deleteBooking(): void
  }

  class "<<Resource>>\nCompanyBookings" as ResourceCompanyBookings {
    <<GET>> +getBookingsForCompany(): Booking
    <<POST>> +addBookingForCompany(): Booking
  }

  class "<<Representation>>\nBooking" as RepresentationBooking {
    -interviewDate
    -userId
    -companyId
    -createdAt
  }
}


' Path mappings

JobFairService ..> ResourceCompanies : "/companies\n<<Path>>"
ResourceCompanies ..> ResourceCompany : "/{companyId}\n<<Path>>"
ResourceCompany ..> RepresentationCompany : "<<use>>"

JobFairService ..> ResourceAuth : "/auth\n<<Path>>"
ResourceAuth ..> RepresentationUser : "<<use>>"
ResourceAuth ..> RepresentationToken : "<<use>>"

JobFairService ..> ResourceBookings : "/bookings\n<<Path>>"
ResourceBookings ..> ResourceBooking : "/{bookingId}\n<<Path>>"
ResourceBooking ..> RepresentationBooking : "<<use>>"

ResourceCompany ..> ResourceCompanyBookings : "/bookings\n<<Path>>"
ResourceCompanyBookings ..> RepresentationBooking : "<<use>>"



@enduml