@startuml Booking For Company (POST)

title "Booking For Company (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:companies" as routerCompanies
participant "<<router>>\n:bookings" as routerBookings
participant "<<controllers>>\n:bookings" as controllersBookings
participant "<<model>>\n:Booking" as modelBooking
database "<<MongoDB>>\n:bookings" as BookingsDatabase

client->server ++:req.post('/api/v1/companies/:companyId/bookings')
server->routerCompanies ++:app.use('/api/v1/companies',companies)
routerCompanies -> routerBookings ++:use('/:companyId/bookings',bookingRouter)
routerBookings -> controllersBookings ++:addBooking()
controllersBookings->modelBooking ++:create(req.body + companyId)
modelBooking ->BookingsDatabase ++: BookingSchema
BookingsDatabase --> modelBooking --: booking
controllersBookings <-- modelBooking --: booking
controllersBookings->client --:response

@enduml